// App
export const UPDATE_SCREENSIZE = "UPDATE_SCREENSIZE";
export const UPDATE_GLOBALNAV_STAT = "UPDATE_GLOBALNAV_STAT";
export const UPDATE_MENUNAV_STAT = "UPDATE_MENUNAV_STAT";
export const ADD_OVERLAY = "ADD_OVERLAY";
export const REMOVE_OVERLAY = "REMOVE_OVERLAY";

// Data
export const UPDATE_CODES = "UPDATE_CODES";
export const UPDATE_CATEGORIES = "UPDATE_CATEGORIES";
export const UPDATE_PICKED = "UPDATE_PICKED";
export const ADD_COMPANY = "ADD_COMPANY";
